# Generated by Django 5.2.3 on 2025-06-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='email',
            new_name='e_email',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='name',
            new_name='e_name',
        ),
        migrations.AddField(
            model_name='employees',
            name='e_contact',
            field=models.IntegerField(default=None, max_length=11),
        ),
    ]
